// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductAdmin.API.DbContexts;

namespace ProductAdmin.API.Migrations
{
    [DbContext(typeof(ProductsAdminContext))]
    [Migration("20210707141733_Migration001")]
    partial class Migration001
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProductAdmin.API.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BuyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<int>("ProductStatus")
                        .HasColumnType("int");

                    b.Property<int>("ProductType")
                        .HasColumnType("int");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<long>("Value")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("01acf2fe-9220-447e-a3d1-f008e71a9423"),
                            BuyDate = new DateTime(2011, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "apartamento con gran amplitud apesar de dimensiones teccnicas, paredes blancas y vista a las montañas",
                            ProductStatus = 0,
                            ProductType = 3,
                            ShortName = "apartamento en barrio alqueria",
                            Value = 111000000L
                        },
                        new
                        {
                            Id = new Guid("5fd19bf5-e24d-4a51-849d-58e44e3c725c"),
                            BuyDate = new DateTime(2012, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Gran lote con casa casi lista para ser demolida y reconstruida",
                            ProductStatus = 0,
                            ProductType = 2,
                            ShortName = "Casa en alqueria la fragua",
                            Value = 222000000L
                        },
                        new
                        {
                            Id = new Guid("513888e3-a5c8-4731-b19d-240623882d49"),
                            BuyDate = new DateTime(2013, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Muebles de casa recien demolida listos para encontrar un nuevo hogar",
                            ProductStatus = 1,
                            ProductType = 0,
                            ShortName = "Muebles para casa",
                            Value = 33000000L
                        },
                        new
                        {
                            Id = new Guid("3b300beb-3ef8-4426-b9c5-88eaf15ed981"),
                            BuyDate = new DateTime(2014, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Primer renault 6 de colombia con placas clasicas, naturalemnte en perfecto estado",
                            ProductStatus = 0,
                            ProductType = 1,
                            ShortName = "Renault 6 clasico",
                            Value = 44000000L
                        },
                        new
                        {
                            Id = new Guid("9d125853-285b-4a7e-b795-f022c10fe326"),
                            BuyDate = new DateTime(2015, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Linto apartamento solo habitado por una pareja de hermanos, grande y queda cerca a dos centros comerciales, el eden y multiplaza",
                            ProductStatus = 1,
                            ProductType = 3,
                            ShortName = "Apartamento calle 13 con boyaca",
                            Value = 555000000L
                        },
                        new
                        {
                            Id = new Guid("895d042a-f4fe-4bb0-9c7a-e2cb773f9f1a"),
                            BuyDate = new DateTime(2016, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fina a las afuera de bogota por el norte, solia estar dedicada a la industria lechera, gangazo",
                            ProductStatus = 0,
                            ProductType = 2,
                            ShortName = "Finca lechera",
                            Value = 660000000L
                        },
                        new
                        {
                            Id = new Guid("a9f2d78a-3f24-4451-a113-e9e144034863"),
                            BuyDate = new DateTime(2021, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Hermosa camioneta gran vitara modelo 20 color rojo, la vendemos por que nos vamos del pais, oferta imperdible",
                            ProductStatus = 0,
                            ProductType = 1,
                            ShortName = "Camioneta gran vitara",
                            Value = 7000000L
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
